services:
  todo:
    build: .
    ports:
      - 8080:8080

  database:
    image: 'postgres:16.1-alpine3.19'
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: password
    # volumes:
    #   - ./db-data/:/var/lib/postgresql/data/
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

