steps:
  lint:
    image: rust:alpine
    commands:
      - rustup component add clippy
      - cargo clippy --verbose
    failure: ignore

  test:
      image: rust:alpine
      commands:
        - apk add libpq-dev 
        - cargo test
    failure: ignore

  build:
    image: rust:alpine
    commands:
      - apk add libpq-dev
      - cargo build --release

when:
  - event: [pull_request, manual]