steps:
  test:
      image: rust
      depends_on: test
      commands:
        - cargo test

  build:
    image: rust
    depends_on: build
    commands:
      - cargo build --release

when:
  - event: [pull_request, manual]