steps:
  lint:
    image: rust
    commands:
      - rustup component add clippy
      - cargo clippy --verbose
    failure: ignore

  test:
    image: rust
    commands:
      - apt install libpq-dev 
      - cargo test
    failure: ignore

  build:
    image: rust
    commands:
      - apt install libpq-dev 
      - cargo build --release

when:
  - event: [pull_request, manual]