steps:
  lint:
    image: rust
    commands:
      - rustup component add clippy
      - cargo clippy --verbose

  test:
      image: rust
      commands:
        - cargo test

  build:
    image: rust
    commands:
      - cargo build --release

when:
  - event: [pull_request, manual]