steps:
  deploy:
      image: docker
      commands:
        - docker compose up -d
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

when:
  - event: [push, manual]
    branch: main