name: "ci"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: todo:latest
          outputs: type=docker,dest=/tmp/todo.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: todo
          path: /tmp/todo.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: todo
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/todo.tar
      - name: Run tests
        run: docker run todo:latest cargo test

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: todo
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/todo.tar
      - name: Run chappy linting
        run: docker run todo:latest sh -c "rustup component add clippy ; cargo clippy"
